apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "teleport-loki.fullname" . }}-event-handler
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "teleport-loki.labels" . | nindent 4 }}